import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/21959167-9095-4D17-95C4-3885293E59A0_1_102_o.jpeg" />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
